<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/2_5_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np

# 2차원 배열 정의
mat1 = [[1, 2, 3, 4],
        [5, 6, 7, 8,]]

mat2 = [[9, 10, 11, 12],
        [13, 14, 15, 16]]

mat3 = [[17, 18, 19, 20],
        [21, 22, 23, 24]]

# 텐서 변환
tensor1 = tf.constant([mat1, mat2, mat3])

print("rank:", tf.rank(tensor1))
print("tensor1:", tensor1)

# 텐서 변환
tensor2 = tf.stack([mat1, mat2, mat3])

print("rank:", tf.rank(tensor2))
print("tensor2:", tensor2)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)
rank: tf.Tensor(3, shape=(), dtype=int32)
tensor2: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [4]:
# 1차원 배열 정의
vec1 = [1, 2, 3, 4]
vec2 = [5, 6, 7, 8]
vec3 = [9, 10, 11, 12]
vec4 = [13, 14, 15, 16]
vec5 = [17, 18, 19, 20]
vec6 = [21, 22, 23, 24]

arr = [[vec1, vec2],
       [vec3, vec4],
       [vec5, vec6]]

# 텐서 변환
tensor3 = tf.constant(arr)

print("rank:", tf.rank(tensor3))
print("tensor1:", tensor3)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [5]:
# 랭크-4 텐서 만들기
tensor4 = tf.stack([tensor1, tensor2])

print("rank:", tf.rank(tensor4))
print("tensor1:", tensor4)       # shape는 순서대로 axis=0,1,2,3(or -1) 방향으로 몇 개의 원소가 들어 있는지 나타냄

rank: tf.Tensor(4, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)
