<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/2_6_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf

# 벡터 정의
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

print(vec[0])
print(vec[-1])
print(vec[:3])

# 행렬 정의
mat = tf.constant([[10, 20, 30],
                   [40, 50, 60]])

print(mat[0,2])
print(mat[0,:])
print(mat[:,1])
print(mat[:,:])


# 랭크-3 텐서 정의
tensor = tf.constant([
                      [[10, 20, 30],
                       [40, 50, 60]],
                      [[-10, -20, -30],
                       [-40, -50, -60]]
])
print(tensor)

print(tensor[0:,:,:])
print(tensor[:,:2,:2])

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor([20 50], shape=(2,), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)
