<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/tf01_1_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

# Computational Graph

텐서플로우 버전 2.0.0에서는 session을 정의하고 run해주는 과정을 생략함

In [ ]:
import tensorflow as tf

node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)     # also tf.float32 implicitly
node3 = tf.add(node1, node2)

In [ ]:
tf.print(node1, node2)
tf.print(node3)

3 4
7


# Placeholder

In [ ]:
import tensorflow as tf
import numpy as np

@tf.function
def adder(a, b):
    return a + b

A = tf.constant(1)
B = tf.constant(2)
print(adder(A, B))

C = tf.constant([1,2])
D = tf.constant([3,4])
print(adder(C, D))

E = tf.constant([[1,2,3], [4,5,6]])
F = tf.constant([[2,3,4], [5,6,7]])
print(adder(E, F))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 3  5  7]
 [ 9 11 13]], shape=(2, 3), dtype=int32)
