<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/tf12_2_char_seq_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

이전의 코드와는 다르게 문자열만 입력해주면 알아서 해주는 코드

In [3]:
import tensorflow as tf
import numpy as np

sample = "if you want you"
idx2char = list(set(sample))     # index -> char
char2idx = {c: i for i, c in enumerate(idx2char)}    # char -> idex(각각의 알파벳의 인덱스를 부여)

# hyper parameters
dic_size = len(char2idx)         # RNN input size (one hot size)
hidden_size = len(char2idx)      # RNN output size
num_classes = len(char2idx)      # final output size (RNN or softmax, etc.)
batch_size = 1       # one sample data, one batch (1개의 문자열)
sequence_length = len(sample) - 1   # number of lstm rollings (unit # -> cell의 개수)
learning_rate = 0.1

sample_idx = [char2idx[c] for c in sample]      # char to index(해당 문자열 순서에 맞게 인덱스 부여)
x_data = [sample_idx[:-1]]        # X_data sample (0 ~ n-1) hello: hell
y_data = [sample_idx[1:]]         # Y label sample (1 ~ n)  hello: ello

x_one_hot_eager = tf.one_hot(x_data, num_classes)
x_one_hot_numpy = tf.keras.utils.to_categorical(x_data, num_classes)
y_one_hot_eager = tf.one_hot(y_data, num_classes)
print(x_one_hot_eager)
print(x_one_hot_eager.shape)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.
             LSTM(units=num_classes, input_shape=(sequence_length, x_one_hot_eager.shape[2]), return_sequences=True))
tf.model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=num_classes, activation='softmax')))
tf.model.summary()
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=learning_rate),
                 metrics=['accuracy']) 
tf.model.fit(x_one_hot_eager, y_one_hot_eager, epochs=50)

predictions = tf.model.predict(x_one_hot_eager)
print(predictions)

for i, prediction in enumerate(predictions):
    # print char using argmax, dict
    result_str = [idx2char[c] for c in np.argmax(prediction, axis=1)]
    print("\tPrediction str: ", ''.join(result_str))

tf.Tensor(
[[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]], shape=(1, 14, 10), dtype=float32)
(1, 14, 10)
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 14, 10)            840       
                                                                 
 time_distributed_1 (TimeDis  (None, 14, 10)           110       
 tributed)                                                       
                                              

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


1/1 [==============================] - 2s 2s/step - loss: 2.2939 - accuracy: 0.1429
Epoch 2/50
1/1 [==============================] - 0s 14ms/step - loss: 2.1291 - accuracy: 0.3571
Epoch 3/50
1/1 [==============================] - 0s 21ms/step - loss: 1.9374 - accuracy: 0.3571
Epoch 4/50
1/1 [==============================] - 0s 9ms/step - loss: 1.7403 - accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 18ms/step - loss: 1.4879 - accuracy: 0.7143
Epoch 6/50
1/1 [==============================] - 0s 14ms/step - loss: 1.2068 - accuracy: 0.6429
Epoch 7/50
1/1 [==============================] - 0s 12ms/step - loss: 0.9002 - accuracy: 0.7857
Epoch 8/50
1/1 [==============================] - 0s 15ms/step - loss: 0.6519 - accuracy: 0.8571
Epoch 9/50
1/1 [==============================] - 0s 13ms/step - loss: 0.4722 - accuracy: 0.9286
Epoch 10/50
1/1 [==============================] - 0s 12ms/step - loss: 0.3264 - accuracy: 0.9286
Epoch 11/50
1/1 [==========================