<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/2_4_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# 2차원 배열 정의
list_of_list = [[10, 20], [30, 40]]

# 텐서 변환
mat1 = tf.constant(list_of_list)

print("rank:", tf.rank(mat1))
print("mat1:", mat1)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat1: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [2]:
# 1차원 벡터 정의
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

# 텐서 변환
mat2 = tf.stack([vec1, vec2])

print("rank:", tf.rank(mat2))
print("mat2:", mat2)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat2: tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [3]:
# element-by-element 연산
element_mul = tf.math.multiply(mat1, mat2)
print("result:", element_mul)
print("rank:", tf.rank(element_mul))

result: tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [4]:
# 브로드캐스팅 연산
element_bc = tf.math.multiply(mat1, 3)
print("result:", element_bc)
print("rank:", tf.rank(element_bc))

result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [5]:
# 행렬곱 연산
mat_mul = tf.matmul(mat1, mat2)
print("result:", mat_mul)
print("rank:", tf.rank(mat_mul))

result: tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [7]:
# 덧셈 연산
add1 = tf.math.add(mat1, mat2)
print("result:", add1)
print("rank:", tf.rank(add1))

add2 = mat1 + mat2
print("result:", add2)
print("rank:", tf.rank(add2))

result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
result: tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [8]:
# 텐서를 넘파이로 변환
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]
