<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/2_8_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

# 텐서 정의
tensor1 = tf.constant([[0, 1, 2],
                       [3, 4, 5]])
print(tensor1)



tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)
print("이름:", tensor_var1.name)
print("크기:", tensor_var1.shape)
print("자료형:", tensor_var1.dtype)
print("배열:", tensor_var1.numpy())

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]], dtype=int32)>
이름: Variable:0
크기: (2, 3)
자료형: <dtype: 'int32'>
배열: [[0 1 2]
 [3 4 5]]


In [6]:
tensor_var1.assign([[1,1,1],
                    [2,2,2]])
print(tensor_var1)


tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

tensor_var2 = tf.Variable(tensor2, name='New Name')
print(tensor_var2.name)

tensor_var1 + tensor_var2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>
tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)
New Name:0


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]], dtype=int32)>