<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/tensorflow/3_13_tensorflow_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 텐서플로 데이터셋
import tensorflow_datasets as tfds

dataset_name = 'cifar100'
ds = tfds.load(dataset_name, split='train')
ds

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/cifar100/3.0.2.incompleteDDWK0H/cifar100-train.tfrecord


  0%|          | 0/50000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/cifar100/3.0.2.incompleteDDWK0H/cifar100-test.tfrecord


  0%|          | 0/10000 [00:00<?, ? examples/s]

Dataset cifar100 downloaded and prepared to /root/tensorflow_datasets/cifar100/3.0.2. Subsequent calls will reuse this data.


<PrefetchDataset element_spec={'coarse_label': TensorSpec(shape=(), dtype=tf.int64, name=None), 'id': TensorSpec(shape=(), dtype=tf.string, name=None), 'image': TensorSpec(shape=(32, 32, 3), dtype=tf.uint8, name=None), 'label': TensorSpec(shape=(), dtype=tf.int64, name=None)}>

In [3]:
# 5개의 데이터 출력
for data in ds.take(5):
    print(data)     # 개별 데이터는 딕셔너리 형태로 이루어짐.

{'coarse_label': <tf.Tensor: shape=(), dtype=int64, numpy=12>, 'id': <tf.Tensor: shape=(), dtype=string, numpy=b'train_16399'>, 'image': <tf.Tensor: shape=(32, 32, 3), dtype=uint8, numpy=
array([[[151, 154, 145],
        [144, 147, 135],
        [141, 143, 134],
        ...,
        [ 44,  38,  39],
        [112, 100,  96],
        [145, 127, 120]],

       [[153, 156, 150],
        [141, 144, 135],
        [139, 142, 136],
        ...,
        [ 68,  59,  59],
        [131, 113, 106],
        [121, 101,  94]],

       [[163, 165, 161],
        [150, 153, 145],
        [147, 149, 144],
        ...,
        [ 75,  66,  60],
        [101,  86,  77],
        [ 83,  77,  73]],

       ...,

       [[150, 150, 162],
        [ 51,  52,  67],
        [ 46,  42,  56],
        ...,
        [ 60,  59,  48],
        [ 71,  73,  56],
        [ 58,  62,  44]],

       [[146, 158, 168],
        [ 92, 106, 116],
        [ 73,  77,  85],
        ...,
        [ 54,  55,  40],
        [ 59,  66,  41],
 

In [4]:
# 5개의 데이터 출력
for data in ds.take(5):
    # image
    image = data['image']
    #label
    label = data['label']
    print(image.shape)
    print(label)       # 0~99 값들로 이루어짐.

(32, 32, 3)
tf.Tensor(66, shape=(), dtype=int64)
(32, 32, 3)
tf.Tensor(23, shape=(), dtype=int64)
(32, 32, 3)
tf.Tensor(40, shape=(), dtype=int64)
(32, 32, 3)
tf.Tensor(39, shape=(), dtype=int64)
(32, 32, 3)
tf.Tensor(7, shape=(), dtype=int64)


다음과 같이 투플 형식으로 dataset 로드 시에 키 값을 확인하지 않아도 되므로 많이 사용되는 옵션이다.

In [5]:
# as_supervised = True는 tuple 형식으로 x, y 데이터 로드
ds = tfds.load(dataset_name, split='train', as_supervised=True)

for image, label in ds.take(5):
    print(image.shape, label)        

(32, 32, 3) tf.Tensor(66, shape=(), dtype=int64)
(32, 32, 3) tf.Tensor(23, shape=(), dtype=int64)
(32, 32, 3) tf.Tensor(40, shape=(), dtype=int64)
(32, 32, 3) tf.Tensor(39, shape=(), dtype=int64)
(32, 32, 3) tf.Tensor(7, shape=(), dtype=int64)


In [7]:
# with_info = True로 데이터셋의 정보 로드
ds, info = tfds.load(dataset_name, split='train', with_info=True)

# info 확인
info

tfds.core.DatasetInfo(
    name='cifar100',
    version=3.0.2,
    description='This dataset is just like the CIFAR-10, except it has 100 classes containing 600 images each. There are 500 training images and 100 testing images per class. The 100 classes in the CIFAR-100 are grouped into 20 superclasses. Each image comes with a "fine" label (the class to which it belongs) and a "coarse" label (the superclass to which it belongs).',
    homepage='https://www.cs.toronto.edu/~kriz/cifar.html',
    features=FeaturesDict({
        'coarse_label': ClassLabel(shape=(), dtype=tf.int64, num_classes=20),
        'id': Text(shape=(), dtype=tf.string),
        'image': Image(shape=(32, 32, 3), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=100),
    }),
    total_num_examples=60000,
    splits={
        'test': 10000,
        'train': 50000,
    },
    supervised_keys=('image', 'label'),
    citation="""@TECHREPORT{Krizhevsky09learningmultiple,
        author = {