<a href="https://colab.research.google.com/github/lala991204/DL-self-study/blob/master/tensorflow/3_14_tf_data_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf

as_numpy_iterator()는 생성된 Dataset 클래스를 numpy 배열로 반환한다.

In [17]:
dataset = tf.data.Dataset.range(10)
print(list(dataset.as_numpy_iterator()))
print('\n')

def filter_five(x):
    return x.filter(lambda x: x < 5)
print(list(dataset.apply(filter_five).as_numpy_iterator()))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 2, 3, 4]


from_tensor_slices는 리스트 혹은 numpy 배열을 Dataset 클래스로 변환해준다.

In [10]:
ds = tf.data.Dataset.from_tensor_slices([1,2,3,4,5])
print(type(ds))
print(list(ds.as_numpy_iterator()))
print('\n')

for d in ds:
    print(d)

<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>
[1, 2, 3, 4, 5]


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [9]:
ds = tf.data.Dataset.range(1, 10, 2)
for d in ds:
    print(d)
print('\n')

ds = tf.data.Dataset.range(8)
for d in ds.batch(3):      # 3개의 요소가 하나의 배치로 구성됨.
    print(d)
print('\n')

for d in ds.batch(3, drop_remainder=True):    # 잔여 요소의 개수가 배치 크기보다 작으면 생성 X
    print(d)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)
tf.Tensor([6 7], shape=(2,), dtype=int64)


tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)


window 메소드는 시계열 dataset 구축시 윈도우 구현에 사용된다.

In [8]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5, shift=1, drop_remainder=False)  # ex: 5일 간의데이터를 묶어 하나의 배치로 구성하고자 할 때(shift: 윈도우 구성의 시작점을 몇 칸씩 건너뛸 것인지!)
for d in ds:
    print(list(d.as_numpy_iterator()))
print('\n')

ds = tf.data.Dataset.range(10)
ds = ds.window(5, shift=1, drop_remainder=True)
for d in ds:
    print(list(d.as_numpy_iterator()))
print('\n')

ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=2, drop_remainder=True)
for d in ds:
    print(list(d.as_numpy_iterator()))

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


[0, 1, 2, 3, 4]
[2, 3, 4, 5, 6]
[4, 5, 6, 7, 8]


flat_map 메소드는 map 함수를 Dataset 클래스에 적용하며 flatten한 결과를 반환한다.

In [12]:
ds = tf.data.Dataset.range(10)
ds = ds.window(5, shift=1, drop_remainder=True)
# ds = ds.flat_map(lambda w: w.batch(5))
for d in ds:
    print(d)
print('\n')

ds = tf.data.Dataset.range(10)
ds = ds.window(5, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda w: w.batch(5))
for d in ds:
    print(d)

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>


tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int64)
tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int64)
tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


In [13]:
# shuffle을 해주지 않은 경우
ds = tf.data.Dataset.from_tensor_slices(np.arange(10))     # .shuffle()
for d in ds:
    print(d)
print('\n')

# shuffle 설정
ds = tf.data.Dataset.from_tensor_slices(np.arange(10)).shuffle(buffer_size=5)
for d in ds:
    print(d)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)


map 메소드는 데이터셋을 입력 데이터와 레이블 데이터로 분리할 때 활용할 수 있다.

In [15]:
window_size = 5

ds = tf.data.Dataset.range(10)
ds = ds.window(window_size, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda w: w.batch(window_size))
ds = ds.shuffle(10)

# 첫 3개와 마지막 2개를 분리
ds = ds.map(lambda x: (x[:-2], x[-2:]))
for x, y in ds:
    print('train set: {}'.format(x))
    print('label set: {}'.format(y))
    print('===' * 10)

train set: [5 6 7]
label set: [8 9]
train set: [0 1 2]
label set: [3 4]
train set: [3 4 5]
label set: [6 7]
train set: [2 3 4]
label set: [5 6]
train set: [1 2 3]
label set: [4 5]
train set: [4 5 6]
label set: [7 8]
